name: gaius-process
on:
  push:
    branches:
      - master
jobs:
  gaius-process:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: '3.1.201'
    - name: Run gaius process
      run: |
        dotnet ./bin/gaius/gaius.dll process -y
    - name: Push generated files to gh-pages branch
      uses: s0/git-publish-subdir-action@v2.2.0
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _generated
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}